### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by sproogen** [voryx/ThruwayBundle#51]
Hi,

We are having this issue after an extended period of inactivity, usually overnight, where when the first query after this period is throwing this error `Warning: PDOStatement::execute(): MySQL server has gone away`

We put in a fix for this by closing and reopening the database connection but this just threw a new issue after the inactivity of `Warning: Error while sending QUERY packet.`

Has anyone had this before or know of a fix for this? It looks like it is happening after the 8 hour wait_timout in mysql.

I have also seen there is a cleanup function in the WampKernel that looks like it should be resetting the connections?

Thanks

**Comment by stingus** [comment]
If you're using Doctrine, you can use the following:
`$em = $this->doctrine->getManager();
$dbalConn = $em->getConnection();
if (!$dbalConn->ping()) {
    $dbalConn->close();
    $dbalConn->connect();
 }`

I had the same issue and the ping() test fixed it. You just need to figure out where to place the test, like an entry point. I use it in an authentication provider (JWT), because all requests triggering connections to MySQL are passing through that method.

**Comment by sproogen** [comment]
Thanks @stingus, it looks like we were doing the close and connect at the start of an action but after the authentication call.

Having moved it to the start of out Authentication Provider it seems to be working.
